export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_CONFLICT: 'USER_CONFLICT',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};
